### ISSUE TITLE
[1.16.5 Error] Can't enter dungeon dimension

### ISSUE THREAD

**Issue by CactusDuud** [AllenSeitz/DimDungeons#27]
Created the portal, but whenever I try to enter, it causes the following log:

```
[Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.catastrophe573.dimdungeons.structure.DungeonBuilderLogic.<init>(DungeonBuilderLogic.java:135) ~[?:1.10]
	at com.catastrophe573.dimdungeons.structure.DungeonPlacementLogicBasic.place(DungeonPlacementLogicBasic.java:74) ~[?:1.10]
	at com.catastrophe573.dimdungeons.utils.DungeonUtils.buildDungeon(DungeonUtils.java:150) ~[?:1.10]
	at com.catastrophe573.dimdungeons.block.BlockPortalKeyhole.func_225533_a_(BlockPortalKeyhole.java:151) ~[?:1.10]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$26331/1431225952.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$25057/1065715789.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Also, right clicking the portal block removes it from existence. Let me know if you need any more info (I am running with a large modpack but I can't pin down which one might be conflicting)

**Comment by AllenSeitz** [comment]
Thank you for the report.

In the common config (dimdungeons-common.toml) there are lists of rooms, expressed as lists of lists of strings, that the dungeon builder can choose from. This is so that players can add and remove rooms.

The error seems to be happening at the step where the lists are converted from text to a nested list. It seems like I don't do any validation on the config file, and if it's empty or malformed this will happen.

Try closing the game or server, deleting this file, and then relaunching the game to recreate the config with default values. I'm very sure that will fix it.

**Comment by CactusDuud** [comment]
Sweet, that worked. Thanks for the help!
