### ISSUE TITLE
Patchouli Guide needs updating to work in 1.20.1

### ISSUE THREAD

**Issue by gardenappl** [AllenSeitz/DimDungeons#72]
The guide book is not working, and this shows up in the log on startup:
```
[10вер.2023 13:25:29.726] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book dimdungeons:guide_book defined by mod dimdungeons, skipping
java.lang.IllegalArgumentException: Book dimdungeons:guide_book has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
        at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:76) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at vazkii.patchouli.forge.common.__ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[Patchouli-1.20.1-81-FORGE.jar%23592!/:1.20.1-81-FORGE]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.1.3.jar%23693!/:?]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.1.3.jar%23692!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

That's with:
```
dimdungeons-178-forge-1.20.0.jar
Patchouli-1.20.1-81-FORGE.jar
```

**Comment by AllenSeitz** [comment]
Thank you! This will be fixed in the next version.

**Comment by AllenSeitz** [comment]
Fixed in v180
